# Compiler definitions
CC = gcc
CCFLAGS = -c -Wall $(addprefix -D,$(DEFINES)) -I$(INCLUDE_DIR) $(MAKEFILE_DEPS_FLAGS)
MAKEFILE_DEPS_FLAGS = -MMD -MP
DEFINES =
LDFLAGS = -lm

# Helper programs
MKDIR_P = mkdir -p

# Directories
SOURCE_DIR = src
INCLUDE_DIR = include
OBJ_DIR = obj

# Files
EXECUTABLE = mmvis
INCLUDES = $(wildcard $(INCLUDE_DIR)/*.h)
SOURCES = $(wildcard $(SOURCE_DIR)/*.c)
OBJECTS = $(SOURCES:$(SOURCE_DIR)/%.c=$(OBJ_DIR)/%.o)
DEPS = $(OBJECTS:.o=.d)

# Phony Targets
.PHONY: dirs all clean

all: dirs $(OBJECTS) $(EXECUTABLE)
	@printf "All done.\n"

clean:
	rm -rf $(OBJ_DIR) $(EXECUTABLE)
	@printf "Cleaned.\n"

dirs: $(OBJ_DIR)

# Real Targets
$(EXECUTABLE): $(OBJECTS)
	@printf "Linking $(EXECUTABLE)...\n"
	$(CC) $(LDFLAGS) $(OBJECTS) -o $(EXECUTABLE)
	@printf "Done.\n\n"

$(OBJ_DIR)/%.o: $(SOURCE_DIR)/%.c
	@printf "Compiling $< ...\n"
	$(CC) $(CCFLAGS) $< -o $@
	@printf "Done.\n\n"

$(OBJ_DIR):
	@printf "Creating output folder...\n"
	$(MKDIR_P) $@;
	@printf "Done.\n\n"

# Include dependency targets generated by (-MMD -MP) flags
-include $(DEPS)
